mydata <- read.table("household_power_consumption.txt", sep=';', header=TRUE)
mydata$Date <- as.Date(mydata$Date,format="%d/%m/%Y")
data <- mydata[mydata$Date=="2007-02-01"|mydata$Date=="2007-02-02",]
data$Global_active_power <- as.numeric(as.character(data$Global_active_power))
data$Global_reactive_power <- as.numeric(as.character(data$Global_reactive_power))
data$Voltage <- as.numeric(as.character(data$Voltage))
data$Global_intensity <- as.numeric(as.character(data$Global_intensity))
data$Sub_metering_1 <- as.numeric(as.character(data$Sub_metering_1))
data$Sub_metering_2 <- as.numeric(as.character(data$Sub_metering_2))
data$newdate <- with(data, as.POSIXct(paste(Date, Time), format="%Y-%m-%d %H:%M:%S"))
png('plot4.png')
par(mfrow=c(2,2))
with(data, {
plot(data$Global_active_power ~ newdate, data=data, type="l", xlab='',ylab="Gobal Active Power")
plot(data$Voltage ~ newdate, data=data, type="l", ylab='Voltage',xlab="datetime")
with(data, plot(newdate,Sub_metering_1,type="l",xlab='', ylab="Energy sub metering"))
with(data, points(newdate,Sub_metering_2,type="l",col="red"))
with(data, points(newdate,Sub_metering_3,type="l",col="blue"))
legend("topright",pch='-', col=c("red", "blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(data$Global_reactive_power ~ newdate, data=data, type="l", xlab='datetime',ylab="Global_reactive_power")
})
dev.off()
