mydata <- read.table("household_power_consumption.txt", sep=';', header=TRUE)
mydata$Date <- as.Date(mydata$Date,format="%d/%m/%Y")
data <- mydata[mydata$Date=="2007-02-01"|mydata$Date=="2007-02-02",]
data$Global_active_power <- as.numeric(as.character(data$Global_active_power))
data$Global_reactive_power <- as.numeric(as.character(data$Global_reactive_power))
data$Voltage <- as.numeric(as.character(data$Voltage))
data$Global_intensity <- as.numeric(as.character(data$Global_intensity))
data$Sub_metering_1 <- as.numeric(as.character(data$Sub_metering_1))
data$Sub_metering_2 <- as.numeric(as.character(data$Sub_metering_2))
data$newdate <- with(data, as.POSIXct(paste(Date, Time), format="%Y-%m-%d %H:%M:%S"))
png('plot2.png')
plot(data$Global_active_power ~ newdate, data=data, type="l", xlab='',ylab="Gobal Active Power (kilowattes)")
dev.off()
